#!/bin/bash
set -e
./code_generate.py
./build test_amplifier 1
./build test_decimation 1
./build test_derivative 1
./build test_dither 1
./build test_fast_tanh 1
./build test_file 1
./build test_fir 1
./build test_integrator 1
./build test_meta_compressor 1
./build test_meta_peakdetection 1
./build test_oversampling 1
./build test_peakfollower 1
./build test_rms 1
./build test_sinc 1
./build test_tanh 1
./build test_waveshaper 1
