#!/bin/bash
set -e
./build test_sinc 1
./build test_derivative 1
./build test_oversampling 1
./build test_integrator 1
./build test_rms 1
./build test_file 1
./build test_decimation 1
./build test_waveshaper 1
./build test_fir 1
./build test_dither 1
