#!/bin/bash

#### inputs
####
#### 0 -> test_* to build / run
#### 1 -> 1 to save to png in reports/ instead of displaying 
####      pyplot
####
####

set -e

echo
echo "( housecleaning ... )"
echo

rm -f *.raw
mkdir output -p
rm -f output/*
echo "" > src/test.h

./code_generate.py $1

echo
echo "( compiling & linking )"
echo

scons

echo
echo "( running test )"
echo

time ./cli

echo
echo "( creating report )"
echo

./report.py $2
