Program(
        'nldproc_cliwrap', 
        [
            'src/nldproc_cliwrap.cpp', 
            'src/whitenoise.cpp',
            'src/waveshaper.cpp',
            'src/volume.cpp'
        ], 
        LIBS=
        [
            'libDSPFilters'
        ], 
        CPPPATH=
        [
            './DSPFilters/include'
        ], 
        LIBPATH='.',
        CPPFLAGS="-Ofast"
 )

